version: '3'

services:
  golang:
    image: golang
    volumes:
      - ./src:/go/src
    ports:
      - "9090:9090"
    command: go run /go/src/main.go
    links: 
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
